version: 2
jobs:
   build:
      docker:
         - image: circleci/python:3.6.4
      steps:
         - checkout
         - run:
            command: |
               pip install -U pip
               pip install -r requirements.txt
         - run:
            command: |
               python manage.py test blog
