version: 2
jobs:
   build:
      docker:
         - image: circleci/python:3.6.4
      steps:
         - checkout
         - run: sudo chown -R circleci:circleci /usr/local/bin
         - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages  
         - run: pip install -U pip
         - run: pip install -r requirements.txt
         - run: python manage.py test blog
