# Generated by Django 2.0.1 on 2018-02-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0002_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
